// storageItems.js

export const storageItems = [
    {
      id: 1,
      name: "Fresh Tomatoes",
      quantity: "200 tons",
      location: "Warehouse A",
      lastChecked: "2024-08-20",
      status: "In Stock",
      image: require('./Images/tomatoes.jpg'),
      description: "Plump and juicy tomatoes, perfect for salads and sauces.",
    },
    {
      id: 2,
      name: "Fresh Carrots",
      quantity: "150 tons",
      location: "Warehouse B",
      lastChecked: "2024-08-18",
      status: "In Stock",
      image: require('./Images/carrots.jpg'),
      description: "Crunchy carrots full of vitamins, great for healthy snacks.",
    },
    {
      id: 3,
      name: "Egyptian Garlic",
      quantity: "100 tons",
      location: "Warehouse C",
      lastChecked: "2024-08-19",
      status: "Out of Stock",
      image: require('./Images/garlic.jpg'),
      description: "Pungent and flavorful garlic from Egypt, perfect for seasoning.",
    },
    {
      id: 4,
      name: "Brussels Sprouts",
      quantity: "80 tons",
      location: "Warehouse D",
      lastChecked: "2024-08-21",
      status: "In Stock",
      image: require('./Images/brussels.jpg'),
      description: "Fresh Brussels sprouts, rich in nutrients and flavor.",
    },
    {
      id: 5,
      name: "Bangladeshi Orange",
      quantity: "120 tons",
      location: "Warehouse E",
      lastChecked: "2024-08-22",
      status: "In Stock",
      image: require('./Images/oranges.jpg'),
      description: "Sweet and tangy oranges, a perfect source of vitamin C.",
    },
    {
      id: 6,
      name: "Fresh Red Peppers",
      quantity: "90 tons",
      location: "Warehouse F",
      lastChecked: "2024-08-20",
      status: "In Stock",
      image: require('./Images/peppers.jpg'),
      description: "Vibrant red peppers, excellent for cooking and salads.",
    },
    {
      id: 7,
      name: "Fresh Potatoes",
      quantity: "300 tons",
      location: "Warehouse G",
      lastChecked: "2024-08-19",
      status: "In Stock",
      image: require('./Images/potatoes.jpg'),
      description: "Starchy potatoes, a staple for many dishes.",
    },
    {
      id: 8,
      name: "Fresh Strawberries",
      quantity: "70 tons",
      location: "Warehouse H",
      lastChecked: "2024-08-20",
      status: "Out of Stock",
      image: require('./Images/strawberries.jpg'),
      description: "Sweet and juicy strawberries, perfect for desserts.",
    },
    {
      id: 9,
      name: "Mixed Vegetables",
      quantity: "250 tons",
      location: "Warehouse I",
      lastChecked: "2024-08-21",
      status: "In Stock",
      image: require('./Images/vegetable.jpg'),
      description: "A healthy mix of fresh vegetables.",
    },
    {
      id: 10,
      name: "Fresh Avocados",
      quantity: "110 tons",
      location: "Warehouse J",
      lastChecked: "2024-08-22",
      status: "In Stock",
      image: require('./Images/avocados.jpg'),
      description: "Creamy and rich avocados, great for guacamole.",
    },
    {
      id: 11,
      name: "Fresh Broccoli",
      quantity: "130 tons",
      location: "Warehouse K",
      lastChecked: "2024-08-19",
      status: "In Stock",
      image: require('./Images/broccoli.jpg'),
      description: "Nutrient-packed broccoli, perfect for a healthy diet.",
    },
  ];
  